const DAYS=['lunedì','martedì','mercoledì','giovedì','venerdì','sabato','domenica'],ICONS={Colazione:'☀️',Spuntino:'🍎',Pranzo:'🥗',Cena:'🍽️'};
const breakfast='Yogurt bianco o greco magro (150 g) oppure latte p.s. HD (200 g) · Avena o fiocchi di farro (40 g)',snack='Frutta fresca (una porzione, 150–200 g)';
const PLAN={
  lunedì:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Insalata mista con tonno al naturale (1 scatoletta piccola) e legumi (150 g precotti) · Pane integrale (50 g)'],['Spuntino',snack],['Cena','Petto di pollo o tacchino (100 g) · Verdura a piacere · Pane integrale (100 g)']],
  martedì:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Formaggio magro HD (100 g) · Verdura a piacere · Pane integrale (100 g)'],['Spuntino',snack],['Cena','Pesce azzurro o bianco (150 g) · Verdura a piacere · Pane integrale (100 g)']],
  mercoledì:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Due uova sode · Verdura a piacere · Pane integrale (100 g)'],['Spuntino',snack],['Cena','Carne magra a piacere (100 g) · Verdura a piacere · Pane integrale (100 g)']],
  giovedì:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Affettato magro (50 g) · Insalata mista con legumi (150 g precotti) · Pane integrale (50 g)'],['Spuntino',snack],['Cena','Pesce azzurro o bianco (150 g) · Verdura a piacere · Pane integrale (100 g)']],
  venerdì:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Ricotta vaccina HD (100 g) · Verdura a piacere · Pane integrale (100 g)'],['Spuntino',snack],['Cena','Petto di pollo o tacchino (100 g) · Verdura a piacere · Pane integrale (100 g)']],
  sabato:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Primo piatto (60 g) con legumi a piacere (100 g precotti oppure 25 g secchi) · Insalata'],['Spuntino',snack],['Cena','Pesce azzurro o bianco (150 g) · Verdura a piacere · Pane integrale (100 g)']],
  domenica:[['Colazione',breakfast],['Spuntino',snack],['Pranzo','Libero'],['Spuntino',snack],['Cena','Due uova sode · Insalata · Pane integrale (100 g)']]
};
const DEFAULT_SHOP=[['Colazione',[['Yogurt magro: 7 × 150 g oppure latte p.s. HD: 7 × 200 g'],['Avena o fiocchi di farro: 280 g']]],['Frutta e verdura',[['Frutta fresca: 14 porzioni (circa 2,1–2,8 kg)'],['Verdure e insalata a piacere: per 13 pasti']]],['Pane e cereali',[['Pane integrale: circa 1,1 kg'],['Pasta, riso o altro primo piatto: 60 g']]],['Proteine',[['Tonno al naturale: 1 scatoletta piccola'],['Legumi: 400 g precotti (oppure equivalente secco)'],['Formaggio magro HD: 100 g'],['Uova: 4'],['Affettato magro: 50 g'],['Ricotta vaccina HD: 100 g'],['Pollo o tacchino: 200 g'],['Pesce azzurro o bianco: 450 g'],['Carne magra: 100 g']]],['Dispensa',[['Olio EVO: circa 21 cucchiai per la settimana']]]];
const KEY='piano-alimentare-spesa-v1';let dayOffset=0,hideDone=false,shopping=loadShopping();const $=id=>document.getElementById(id);
function mondayIndex(date){return(date.getDay()+6)%7}function selectedDate(){const d=new Date();d.setDate(d.getDate()+dayOffset);return d}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function mealMarkup(meals,compact=false){return meals.map(([name,text])=>`<article class="meal"><div class="meal-icon">${ICONS[name]}</div><div><h3>${name}</h3><p>${esc(text)}</p></div></article>`).join('')}
function renderToday(){const d=selectedDate(),index=mondayIndex(d),tomorrow=(index+1)%7;$('fullDate').textContent=new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric'}).format(d);$('dayName').textContent=DAYS[index];$('todayMeals').innerHTML=mealMarkup(PLAN[DAYS[index]]);$('tomorrowTitle').textContent=`Per ${DAYS[tomorrow]}`;$('tomorrowMeals').innerHTML=mealMarkup(PLAN[DAYS[tomorrow]])}
function renderWeek(){$('weekList').innerHTML=DAYS.map((day,i)=>`<article class="day-card"><button class="day-button"><strong>${day}</strong><span>${PLAN[day][2][1]==='Libero'?'Pranzo libero':'5 momenti'} &nbsp;⌄</span></button><div class="day-details">${mealMarkup(PLAN[day])}</div></article>`).join('');document.querySelectorAll('.day-button').forEach((b,i)=>b.onclick=()=>b.parentElement.classList.toggle('open'))}
function loadShopping(){try{return JSON.parse(localStorage.getItem(KEY))||makeShopping()}catch{return makeShopping()}}function makeShopping(){return DEFAULT_SHOP.flatMap(([section,items])=>items.map(([text])=>({id:crypto.randomUUID(),section,text,checked:false}))) }function saveShopping(){localStorage.setItem(KEY,JSON.stringify(shopping));renderShopping()}
function renderShopping(){const sections=[...new Set(shopping.map(x=>x.section))];$('shoppingList').innerHTML=sections.map(section=>`<section class="shop-section"><h3>${esc(section.toUpperCase())}</h3>${shopping.filter(x=>x.section===section).map(x=>`<label class="shop-item ${x.checked?'checked':''} ${hideDone&&x.checked?'hidden':''}"><input type="checkbox" data-shop="${x.id}" ${x.checked?'checked':''}><span>${esc(x.text)}</span></label>`).join('')}</section>`).join('');document.querySelectorAll('[data-shop]').forEach(i=>i.onchange=()=>{shopping.find(x=>x.id===i.dataset.shop).checked=i.checked;saveShopping()});const done=shopping.filter(x=>x.checked).length;$('shoppingProgress').textContent=`${done} di ${shopping.length} prodotti presi`;$('hideChecked').textContent=hideDone?'Mostra tutti':'Nascondi presi'}
function setPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===id));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));scrollTo({top:0,behavior:'smooth'})}
$('previousDay').onclick=()=>{dayOffset--;renderToday()};$('nextDay').onclick=()=>{dayOffset++;renderToday()};document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>setPage(b.dataset.nav));$('hideChecked').onclick=()=>{hideDone=!hideDone;renderShopping()};$('resetShopping').onclick=()=>{if(confirm('Ripristinare la lista settimanale?')){shopping=makeShopping();saveShopping()}};$('addItemForm').onsubmit=e=>{e.preventDefault();const text=$('newItem').value.trim();if(text){shopping.push({id:crypto.randomUUID(),section:'Aggiunti da me',text,checked:false});$('newItem').value='';saveShopping()}};$('settingsButton').onclick=()=>$('infoDialog').showModal();$('closeInfo').onclick=()=>$('infoDialog').close();$('exportShopping').onclick=()=>{const text=shopping.filter(x=>!x.checked).map(x=>`☐ ${x.text}`).join('\n'),blob=new Blob([text],{type:'text/plain'}),a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:'lista-spesa.txt'});a.click();URL.revokeObjectURL(a.href)};
renderToday();renderWeek();renderShopping();
