const DIARY_KEY='piano-alimentare-diario-v1',FOODS_KEY='piano-alimentare-alimenti-v1',DIARY_SETTINGS_KEY='piano-alimentare-diario-impostazioni-v1';
const DIARY_MEALS=['Colazione','Spuntino mattina','Pranzo','Spuntino pomeriggio','Cena','Extra'];
let diaryOffset=0,diaryEntries=readLocal(DIARY_KEY,[]),foodCatalog=readLocal(FOODS_KEY,[]),diarySettings=readLocal(DIARY_SETTINGS_KEY,{calorieGoal:null});
function readLocal(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function writeLocal(key,value){localStorage.setItem(key,JSON.stringify(value))}
function diaryUid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function parseDiaryNumber(value){const number=Number(String(value).trim().replace(/\s/g,'').replace(',','.'));return Number.isFinite(number)?number:NaN}
function localIso(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function diaryDate(){const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+diaryOffset);return date}
function diaryDateKey(){return localIso(diaryDate())}
function calculateEntryCalories(){const quantity=parseDiaryNumber($('diaryQuantity').value),per100=parseDiaryNumber($('diaryKcal100').value),calories=quantity>0&&per100>=0?Math.round(quantity*per100)/100:0;$('entryCalories').textContent=new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(calories);return calories}
function diaryMarkup(){return`<section class="page" data-page="diary"><div class="page-heading diary-heading"><p class="eyebrow">DIARIO ALIMENTARE</p><h2>Calorie della giornata</h2><p>Il calcolo usa quantità e kcal per 100 g indicate da te.</p></div><div class="date-head diary-date"><button id="previousDiaryDay">‹</button><div><p id="diaryFullDate"></p><h2 id="diaryDayName"></h2></div><button id="nextDiaryDay">›</button></div><section class="calorie-summary"><span>CALORIE REGISTRATE</span><strong><span id="dailyCalories">0</span> kcal</strong><div class="calorie-meta"><span id="calorieGoalText">Obiettivo non impostato</span><span id="caloriePercent"></span></div><div class="calorie-progress"><i id="calorieProgress"></i></div><button id="setCalorieGoal">Imposta obiettivo</button></section><div id="diaryMeals"></div><button class="diary-add" id="addDiaryEntry">+ Aggiungi alimento</button><p class="diary-disclaimer">Le calorie dipendono dai valori inseriti e possono variare per marca e preparazione.</p></section>`}
function dialogMarkup(){return`<dialog id="diaryDialog"><form class="dialog-card" id="diaryForm"><div class="dialog-head"><div><p class="eyebrow">DIARIO</p><h2 id="diaryDialogTitle">Aggiungi alimento</h2></div><button type="button" id="closeDiary">×</button></div><input type="hidden" id="diaryEntryId"><label class="field"><span>Momento della giornata</span><select id="diaryMeal">${DIARY_MEALS.map(meal=>`<option>${meal}</option>`).join('')}</select></label><label class="field"><span>Alimento</span><input id="diaryFood" list="foodCatalog" maxlength="60" placeholder="Es. yogurt bianco" autocomplete="off" required><datalist id="foodCatalog"></datalist></label><div class="field-grid"><label class="field"><span>Quantità (g/ml)</span><input id="diaryQuantity" inputmode="decimal" placeholder="Es. 150" required></label><label class="field"><span>Kcal per 100 g/ml</span><input id="diaryKcal100" inputmode="decimal" placeholder="Dall'etichetta" required></label></div><div class="calorie-preview"><span>Calorie della porzione</span><strong><span id="entryCalories">0</span> kcal</strong></div><button class="primary" type="submit">Salva nel diario</button><button class="delete-entry hidden" type="button" id="deleteDiaryEntry">Elimina alimento</button></form></dialog><dialog id="goalDialog"><form class="dialog-card" id="goalForm"><div class="dialog-head"><h2>Obiettivo calorie</h2><button type="button" id="closeGoal">×</button></div><p>Inserisci solo un obiettivo concordato con la tua professionista. Puoi lasciarlo vuoto per usare il diario senza limite.</p><label class="field"><span>Kcal giornaliere</span><input id="calorieGoal" inputmode="numeric" placeholder="Facoltativo"></label><button class="primary" type="submit">Salva obiettivo</button></form></dialog>`}
document.querySelector('[data-page="shopping"]').insertAdjacentHTML('beforebegin',diaryMarkup());
document.querySelector('[data-nav="week"]').insertAdjacentHTML('beforebegin','<button data-nav="diary"><span>◷</span>Diario</button>');
document.body.insertAdjacentHTML('beforeend',dialogMarkup());
document.querySelector('[data-nav="diary"]').onclick=()=>{setPage('diary');renderDiary()};
function renderCatalog(){$('foodCatalog').innerHTML=foodCatalog.sort((a,b)=>a.name.localeCompare(b.name,'it')).map(item=>`<option value="${esc(item.name)}"></option>`).join('')}
function renderDiary(){const date=diaryDate(),key=diaryDateKey(),entries=diaryEntries.filter(entry=>entry.date===key),total=entries.reduce((sum,entry)=>sum+entry.calories,0),goal=Number(diarySettings.calorieGoal)||0,percent=goal?Math.round(total/goal*100):0;$('diaryFullDate').textContent=new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric'}).format(date);$('diaryDayName').textContent=new Intl.DateTimeFormat('it-IT',{weekday:'long'}).format(date);$('dailyCalories').textContent=new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(total);$('calorieGoalText').textContent=goal?`${Math.max(goal-total,0).toLocaleString('it-IT',{maximumFractionDigits:1})} kcal rimanenti`:'Obiettivo non impostato';$('caloriePercent').textContent=goal?`${percent}% di ${goal.toLocaleString('it-IT')} kcal`:'';$('calorieProgress').style.width=goal?`${Math.min(percent,100)}%`:'0%';$('calorieProgress').classList.toggle('over',goal>0&&total>goal);$('setCalorieGoal').textContent=goal?'Modifica obiettivo':'Imposta obiettivo';$('diaryMeals').innerHTML=DIARY_MEALS.map(meal=>{const items=entries.filter(entry=>entry.meal===meal),subtotal=items.reduce((sum,entry)=>sum+entry.calories,0);return`<section class="diary-meal"><div class="diary-meal-head"><h3>${meal}</h3><span>${new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(subtotal)} kcal</span></div>${items.length?items.map(entry=>`<button class="diary-entry" data-diary-entry="${entry.id}"><span><strong>${esc(entry.food)}</strong><small>${entry.quantity.toLocaleString('it-IT')} g/ml · ${entry.kcalPer100.toLocaleString('it-IT')} kcal/100</small></span><span>${entry.calories.toLocaleString('it-IT',{maximumFractionDigits:1})} kcal</span></button>`).join(''):'<p class="empty-meal">Nessun alimento registrato</p>'}</section>`}).join('');document.querySelectorAll('[data-diary-entry]').forEach(button=>button.onclick=()=>openDiaryEntry(button.dataset.diaryEntry));renderCatalog()}
function openDiaryEntry(id=null,meal='Colazione'){const entry=id?diaryEntries.find(item=>item.id===id):null;$('diaryForm').reset();$('diaryEntryId').value=entry?.id||'';$('diaryMeal').value=entry?.meal||meal;$('diaryFood').value=entry?.food||'';$('diaryQuantity').value=entry?String(entry.quantity).replace('.',','):'';$('diaryKcal100').value=entry?String(entry.kcalPer100).replace('.',','):'';$('diaryDialogTitle').textContent=entry?'Modifica alimento':'Aggiungi alimento';$('deleteDiaryEntry').classList.toggle('hidden',!entry);calculateEntryCalories();$('diaryDialog').showModal();setTimeout(()=>$('diaryFood').focus(),100)}
function closeDiaryDialog(){$('diaryDialog').close();$('diaryForm').reset()}
$('previousDiaryDay').onclick=()=>{diaryOffset--;renderDiary()};$('nextDiaryDay').onclick=()=>{diaryOffset++;renderDiary()};$('addDiaryEntry').onclick=()=>openDiaryEntry();$('closeDiary').onclick=closeDiaryDialog;
for(const id of['diaryQuantity','diaryKcal100'])$(id).addEventListener('input',calculateEntryCalories);
$('diaryFood').addEventListener('input',()=>{const found=foodCatalog.find(item=>item.name.toLocaleLowerCase('it')===$('diaryFood').value.trim().toLocaleLowerCase('it'));if(found){$('diaryKcal100').value=String(found.kcalPer100).replace('.',',');calculateEntryCalories()}});
$('diaryForm').onsubmit=event=>{event.preventDefault();const food=$('diaryFood').value.trim(),quantity=parseDiaryNumber($('diaryQuantity').value),kcalPer100=parseDiaryNumber($('diaryKcal100').value),calories=calculateEntryCalories();if(!food||!(quantity>0)||!(kcalPer100>=0))return alert('Completa alimento, quantità e calorie per 100 g.');const id=$('diaryEntryId').value,entry={id:id||diaryUid(),date:diaryDateKey(),meal:$('diaryMeal').value,food,quantity:Math.round(quantity*100)/100,kcalPer100:Math.round(kcalPer100*100)/100,calories:Math.round(calories*10)/10,createdAt:Date.now()};if(id)diaryEntries=diaryEntries.map(item=>item.id===id?{...item,...entry,createdAt:item.createdAt}:item);else diaryEntries.push(entry);const known=foodCatalog.find(item=>item.name.toLocaleLowerCase('it')===food.toLocaleLowerCase('it'));if(known){known.name=food;known.kcalPer100=entry.kcalPer100;known.lastUsedAt=Date.now()}else foodCatalog.push({name:food,kcalPer100:entry.kcalPer100,lastUsedAt:Date.now()});writeLocal(DIARY_KEY,diaryEntries);writeLocal(FOODS_KEY,foodCatalog);closeDiaryDialog();renderDiary()};
$('deleteDiaryEntry').onclick=()=>{const id=$('diaryEntryId').value;if(id&&confirm('Eliminare questo alimento dal diario?')){diaryEntries=diaryEntries.filter(item=>item.id!==id);writeLocal(DIARY_KEY,diaryEntries);closeDiaryDialog();renderDiary()}};
$('setCalorieGoal').onclick=()=>{$('calorieGoal').value=diarySettings.calorieGoal||'';$('goalDialog').showModal()};$('closeGoal').onclick=()=>$('goalDialog').close();$('goalForm').onsubmit=event=>{event.preventDefault();const value=$('calorieGoal').value.trim(),goal=value?parseDiaryNumber(value):null;if(value&&!(goal>0))return alert('Inserisci un obiettivo valido oppure lascia vuoto.');diarySettings.calorieGoal=goal?Math.round(goal):null;writeLocal(DIARY_SETTINGS_KEY,diarySettings);$('goalDialog').close();renderDiary()};
renderDiary();
